# This .travis.yml is based on LOOT's .travis.yml:
# https://github.com/loot/loot/blob/dev/.travis.yml
# but see also at:
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?
 

# We are dealing with a C++ project.
language: cpp

# Use Ubuntu 14.04.5 LTS (Trusty Tahr) instead of Ubuntu 12.04.5 LTS (Precise Pangolin)
dist: trusty
sudo: required

# We're going to need cmake etc. for all configurations
addons:
  apt:
    sources: &default_sources
      - ubuntu-toolchain-r-test
    packages: &default_packages
      - cmake
      - libboost-all-dev

matrix:
  include:
   
    - os: linux
      compiler: gcc
      env: CC='gcc-6' CXX='g++-6'
      addons:
        apt:
          sources:
            - *default_sources
          packages: [ *default_packages, gcc-6, g++-6 ]

    - os: linux
      compiler: clang
      env: CC='clang-3.8' CXX='clang++-3.8'
      addons:
        apt:
          sources: 
            - *default_sources
            - llvm-toolchain-trusty
          packages:
            - *default_packages
            - clang-3.8
            - clang++-3.8
            - libstdc++-6-dev

    - os: linux
      compiler: clang
      env: CC='clang-4.0' CXX='clang++-4.0'
      addons:
        apt:
          sources:
            - *default_sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *default_packages
            - clang-4.0
            - clang++-4.0
            - libstdc++-6-dev

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CC='cc' CXX='c++' CLANGSOURCE=APPLE
       
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CC='/usr/local/bin/clang-3.8' CXX='/usr/local/bin/clang++-3.8' CLANGSOURCE=LLVM
            
before_install:
  # Check commit matches expected commit (because of Travis bug)
  - if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)" ]]; then echo "Commit $(git rev-parse HEAD) doesn't match expected commit $TRAVIS_COMMIT"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CLANGSOURCE" == "LLVM" ]]; then brew update && brew install --with-clang llvm38 && brew link --force --overwrite llvm38; fi

script:
  - PARALLEL_MAKE=-j2 make install
  - make test
